### ISSUE TITLE
Ex1. 각자 자기 아이디로 만들어진 파일을 생성하고, 이메일 주소를 기입합니다.

### ISSUE THREAD

**Issue by skonmeme** [sktivd/collabExample#1]
1. branch 만들기
2. users 디렉토리에 파일생성 및 이메일 주소 기입
3. commit
4. pull-request
5. 논의
6. merge

위의 단계를 거쳐서 파일이 master에 생성되어야 합니다.
이 절차를 거치지 않으면 롤백하겠습니다.

**Comment by skonmeme** [comment]
현재까지 한상조M만 진행되었습니다. (실수로 Pull-request가 닫혔습니다.)

**Comment by bacillust** [comment]
SourceTree 프로그램을 통해서, pull을 했더니 에러가 나면서 진행되지 않네요. 
Manual로 "TG_branch2" branch에 "bacillust" 파일은 생성 후에 push 했습니다. 
위의 5번 단계 "논의"는 뭘 의미하나요?
이성곤M님과 논의 후에 진행하라는 건가요?

**Comment by sangjohan** [comment]
Pull Request를  실행하면 bacillust 님의 브랜치를 'master'에 Merge하기 전에 논의(conversation)창이 열립니다. 여기서 논의 후에 정책에 맞게 기능이 추가 됐는지 오류는 없는 지 검토하고 merge 결정을 하는  겁니다. 논의는 그 것을 말하는 거예요

**Comment by skonmeme** [comment]
완료
