### ISSUE TITLE
Ex2. 다른 아이디로 만들어진 파일에 응원의 메세지를 추가합니다.

### ISSUE THREAD

**Issue by skonmeme** [sktivd/collabExample#2]
1. branch 만들기
2. 다른 아이디의 파일에 응원 메세지 기입
3. commit
4. pull-request
5. 논의
6. merge
위의 단계를 거쳐서 master에 수정사항이 merge 되어야 합니다.
이 절차를 거치지 않으면 롤백하겠습니다.

**Comment by bacillust** [comment]
요것도 "TG_for_cheering" branch 만들어서 4번까지는 했습니다. 
5번은 PM (이성곤M)에게 manual로 문의해야 하나요?

**Comment by sangjohan** [comment]
push가 아니라 pull-request를 해야되요...그래요 논의창이 열립니다^^
