### ISSUE TITLE
branch_sjhan 삭제해 주세요

### ISSUE THREAD

**Issue by sangjohan** [sktivd/collabExample#21]
초기에 뭐 모를 때 만든 거라 ... 근데 로컬에서는 지웠는 데 원격지에는 지워지는 게 동기화 안되나 보네요... 자기가 만든 branch를 원격지에서도 지우려면 어떻게 해야 하나요?

**Comment by skonmeme** [comment]
이미 master로 merge가 완료된 branch입니다.
local repository와 remote repository는 branch를 공유하는 것이 아니라 별개의 것입니다.
원격지 branch를 직접 선택한 후 삭제를 하시면 됩니다. 타 브랜치로 merge가 안된 브랜치를 삭제 락이 걸려있는데, 강제 삭제 명령을 내리면 됩니다.
전 멤버에게 쓰기 권한이 주어져 있기 때문에 원격지 branch 삭제도 직접 할 수 있습니다.
다만 요청이 있었던 관계로 제가 삭제하였습니다.
