### ISSUE TITLE
ex1/ex2과 ex3 숙제 함께 pull request 되어 있는 상황입니다.

### ISSUE THREAD

**Issue by sangjohan** [sktivd/collabExample#22]
ex1/ex2가 master에 Merge되지 않은 상태에서 ex3 숙제 내용을 커밋했습니다. 그래서 ex1/ex2 와 ex3가 혼재하고 있는 상황이 되어 버렸네요. 관리자께서 ex1/ex2 merge 후에 ex3 따로 merge 한다고 하셨는데  어떻게 하면 좋을 까요?

**Comment by skonmeme** [comment]
기존 작업 내용으로 revoke을 해서 새로운 commit을 하거나 HEAD를 reset하는 방식으로 기존의 코드로 돌아갈 수 있습니다.
그 다음에 branch를 다시 하고 관련 pull-request를 다시 하시면 됩니다.

**Comment by skonmeme** [comment]
Reset은 개인 개발시 관리가 편하다는 장점이 있으나, 다수의 개발자와 개발시 혼란을 유발할 수 있습니다. 타 개발자가 이미 pull했을 때, reset하는 경우는 재앙적인 상황이 발생합니다. (따라서 작업은 꼭 새 브랜치를 만들고 작업하시는 것이 좋습니다. 본인만이 쓰는 브랜치에서는 reset을 해도 큰 문제가 발생하지 않습니다.)
이럴 우려가 있을 때 사용하는 것이 revoke입니다. 기존 코드로 돌아가도록 새 코드를 작성하는 방식으로, 추가된 것은 지우고, 지운 것은 다시 써서 기존 코드로 돌아가는 것입니다. commit & push하면 새로운 history가 만들어지지만 타 개발자와 충돌이 나지는 않습니다.
